## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
fig = gmaps.figure()

In [3]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Nikolskoye,RU,59.7035,30.7861,45.39,98,100,5.08,overcast clouds
1,1,Rikitea,PF,-23.1203,-134.9692,75.25,69,94,19.60,overcast clouds
2,2,Port Elizabeth,ZA,-33.9180,25.5701,52.09,93,0,2.30,clear sky
3,3,Kalulushi,ZM,-12.8378,28.0919,36.77,71,0,3.58,clear sky
4,4,Albany,US,42.6001,-73.9662,69.62,88,81,4.27,moderate rain

In [4]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [5]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Rikitea,PF,-23.1203,-134.9692,75.25,69,94,19.60,overcast clouds
13,13,Oussouye,SN,12.4850,-16.5469,75.07,75,21,7.14,few clouds
20,20,San Policarpo,PH,12.1791,125.5072,83.64,78,100,5.68,overcast clouds
21,21,Vaini,TO,-21.2000,-175.2000,78.96,69,20,10.36,few clouds
22,22,Butaritari,KI,3.0707,172.7902,83.59,79,74,18.86,light rain
23,23,Maracanau,BR,-3.8767,-38.6256,82.06,78,0,4.99,clear sky
24,24,Bozdar,PK,27.1828,68.6360,86.07,48,3,9.84,clear sky
28,28,Ixtapa,MX,20.7000,-105.2000,81.63,74,1,11.50,clear sky
30,30,Dezful,IR,32.3811,48.4058,81.73,21,0,4.09,clear sky
36,36,Bengkulu,ID,-3.8004,102.2655,81.91,73,40,3.89,scattered clouds

In [6]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                212
City                   212
Country                212
Lat                    212
Lng                    212
Max Temp               212
Humidity               212
Cloudiness             212
Wind Speed             212
Current Description    212
dtype: int64

In [7]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df.count()

City_ID                212
City                   212
Country                212
Lat                    212
Lng                    212
Max Temp               212
Humidity               212
Cloudiness             212
Wind Speed             212
Current Description    212
dtype: int64

In [8]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Rikitea,PF,75.25,overcast clouds,-23.1203,-134.9692,
13,Oussouye,SN,75.07,few clouds,12.4850,-16.5469,
20,San Policarpo,PH,83.64,overcast clouds,12.1791,125.5072,
21,Vaini,TO,78.96,few clouds,-21.2000,-175.2000,
22,Butaritari,KI,83.59,light rain,3.0707,172.7902,
23,Maracanau,BR,82.06,clear sky,-3.8767,-38.6256,
24,Bozdar,PK,86.07,clear sky,27.1828,68.6360,
28,Ixtapa,MX,81.63,clear sky,20.7000,-105.2000,
30,Dezful,IR,81.73,clear sky,32.3811,48.4058,
36,Bengkulu,ID,81.91,scattered clouds,-3.8004,102.2655,

In [9]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    print("------------------------")   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        
    except (IndexError):
        print("Hotel not found... skipping.")

------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
Hotel not found... skipping.
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
Hotel not found... skipping.
------------------------
------------------------
------------------------
------------------------
Hotel not found... skipping.
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
Hotel not found... skipping.
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
Hotel not found... skipping.
------------------------
------------------------
------------------------
------------------------
Hotel not found... skipping.
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
Hotel not found... skipping.
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
Hotel not found... skipping.
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
Hotel not found... skipping.
------------------------
------------------------
------------------------
Hotel not found... skipping.
------------------------
Hotel not found... skipping.
------------------------
------------------------
Hotel not found... skipping.
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
Hotel not found... skipping.
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------
------------------------

In [10]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()

In [11]:
# 8a. Create the output File (CSV)
output_data_file = "Weather_Database/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [12]:
#clean_hotel_df.count()
#max_temp
#clean_hotel_df["Max Temp"]
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Rikitea,PF,75.25,overcast clouds,-23.1203,-134.9692,Pension Maro'i
13,Oussouye,SN,75.07,few clouds,12.4850,-16.5469,Auberge du Routard
20,San Policarpo,PH,83.64,overcast clouds,12.1791,125.5072,JM Lodge
21,Vaini,TO,78.96,few clouds,-21.2000,-175.2000,Keleti Beach Resort
22,Butaritari,KI,83.59,light rain,3.0707,172.7902,Isles Sunset Lodge
...,...,...,...,...,...,...,...
692,Bairiki,KI,87.80,light rain,1.3292,172.9752,Tarawa Boutique Hotel
697,Boffa,GN,79.07,overcast clouds,10.1667,-14.0333,Hôtel Niara Belly
701,San Clemente,US,79.74,scattered clouds,33.4270,-117.6120,Casablanca Inn
702,Isabela,PH,82.09,broken clouds,6.7085,121.9711,Isawad Resort
709,Bonthe,SL,80.56,overcast clouds,7.5264,-12.5050,Bonthe Holiday Village

In [13]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F and {Current Description}</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [15]:
# 11a. Add a marker layer for each city to the map. 
#heat_layer = gmaps.heatmap_layer(locations, weights=clean_hotel_df["Max Temp"], dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
#fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F and {Current Description}</dd>
</dl>
"""

hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
# 11b. Display the figure

fig

Figure(layout=FigureLayout(height='420px'))